### ISSUE TITLE
Migrating to expo

### ISSUE THREAD

**Issue by mun3** [react-native-community/rncamera-example#10]
I'm trying to test several aspects in expo as well (for debugging). Can this project be migrated to expo as per the instructions https://github.com/react-native-community/react-native-camera/blob/master/docs/Expo_Usage.md ?

**Comment by n1ru4l** [comment]
This example is for showcasing react-native-camera so it does not make sense to convert it using expo.

**Comment by sibelius** [comment]
you can try this example https://github.com/expo/camerja to test expo camera

we could also have the same example using react-native-camera to show the difference

`camerja-rncamera`
