### ISSUE TITLE
Missing CAMERA permission

### ISSUE THREAD

**Issue by mun3** [react-native-community/rncamera-example#11]
The [AndroidManifest.xml](https://github.com/react-native-community/rncamera-example/blob/master/android/app/src/main/AndroidManifest.xml) is missing the `android.permission.CAMERA` permission, yet `debug/AndroidManifest.xml` contains many more permissions, e.g., `android.permission.CAMERA`, `android.permission.WRITE_EXTERNAL_STORAGE`, etc. How are the extra permissions generated when they're not stated in AndroidManifest.xml?

**Comment by sibelius** [comment]
I think Camera and other permissions are asked using PermissionModule from Android 6

check this https://github.com/react-native-community/react-native-camera/blob/master/src/handlePermissions.js#L14

I don't think we need WRITE_EXTERNAL_STORAGE, as we save in a temp directory

**Comment by mun3** [comment]
@sibelius Right. Can I also ask how come when `targetSdkVersion` is set to `26` at https://github.com/react-native-community/rncamera-example/blob/master/android/app/src/main/AndroidManifest.xml#L12 `targetSdkVersion` in `debug/AndroidManifest.xml` is set to `22`?

**Comment by sibelius** [comment]
we can just remove those lines https://github.com/react-native-community/rncamera-example/blob/master/android/app/src/main/AndroidManifest.xml#L10-L12

**Comment by mun3** [comment]
Thanks.
