### ISSUE TITLE
Not working on iOS(iPhone 6)

### ISSUE THREAD

**Issue by telmen** [react-native-community/rncamera-example#19]
after a fresh installation and run, faced this crash
```
->  0x19c6144c8 <+628>: stp    q7, q16, [x0]
```
```
Thread 6: EXC_BAD_ACCESS (code=1, address=0x107d5c000)
```

**Comment by felixakiragreen** [comment]
@telmen how did you resolve this? I think I have a similar issue:
<img width="848" alt="screen shot 2019-01-14 at 11 16 31" src="https://user-images.githubusercontent.com/1843672/51125206-21e7b780-17ee-11e9-9c0a-11f24103ec07.png">

Fresh installation, the preview shows up but I can't click any buttons.

(iPhone SE, iOS 12.1)

**Comment by telmen** [comment]
Did you install the library with Pod?

**Comment by telmen** [comment]
Somehow issue is gone. You can try unlink custom linking and re-install the library with Podfile. And make it sure that RNCamera defaultVideoQuality to 720p

**Comment by felixakiragreen** [comment]
I solved it, it was a permission issue.

The documentation says:
```
<key>NSCameraUsageDescription</key>
<string>Your message to user when the camera is accessed for the first time</string>

<!-- Include this only if you are planning to use the camera roll -->
<key>NSPhotoLibraryUsageDescription</key>
<string>Your message to user when the photo library is accessed for the first time</string>

<!-- Include this only if you are planning to use the microphone for video recording -->
<key>NSMicrophoneUsageDescription</key>
<string>Your message to user when the microphone is accessed for the first time</string>
```

But in my experience all three are **required** and the second two are not optional.
