### ISSUE TITLE
[Question]Face Detection not work on android?

### ISSUE THREAD

**Issue by pi-chan** [react-native-community/rncamera-example#4]
Just tried to run on android on 4f87d52 .

It almost worked, but face landmarks and face rects were not rendered.
How to reproduce this problem is very simple, 

- clone
- yarn
- react-native link (optinal ?)
- open the build.gradle file in Android Studio, and Run app.

**Comment by jgfidelis** [comment]
no need to link. Just clone, `yarn install` and `react-native run-android`

**Comment by jgfidelis** [comment]
I will try this tomorrow when I have access to a physical device

**Comment by pi-chan** [comment]
Excuse me, I forgot to list one process.

Run `yarn add react-native-camera@1.0.1` after `yarn install`, because the package version is locked to 0.13.0.

**Comment by pi-chan** [comment]
Revised version of how to reproduce.

- clone
- yarn install
- yarn add react-native-camera@1.0.1
- react-native run-android

**Comment by pi-chan** [comment]
Sorry, this doesn't happen again.
My face is detected almost correctly.
//  It seems that detected landmarks are placed on the incorrect position, because of scale or offset of the preview
