### ISSUE TITLE
New example of new version 0.52, 0.53, 0.54 React Native?

### ISSUE THREAD

**Issue by ducpt2** [react-native-community/rncamera-example#5]
I rely when use one of these version, i can't use the same config in React Native version 0.51.
Can you update the example config for the new version of React Native?
Many thanks.

**Comment by sibelius** [comment]
Feel free to send a PR for this

**Comment by ducpt2** [comment]
@sibelius  sorry but i can't config successful with those new version of React Native. Any one can help pls? :)
