### ISSUE TITLE
invalid prop googleVisionBarcodeType supplied

### ISSUE THREAD

**Issue by m00kid** [react-native-community/rncamera-example#7]
I am trying to get the facedetector example to work on android. After cloning and running on my device I get stuck on this error. 
![googlevisionbarcode](https://user-images.githubusercontent.com/4762104/38608847-1a128c0c-3daf-11e8-83a6-876bee954f0c.png)

Any help appreciated, have been looking to solve this for several hours now to no avail...

 package.json:
  "dependencies": {
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-camera": "git+https://git@github.com/react-native-community/react-native-camera"
  }

**Comment by Covenanter** [comment]
+1

**Comment by marcusbelcher** [comment]
Open Issue in the library itself (https://github.com/react-native-community/react-native-camera/issues/1461)

Add ` googleVisionBarcodeType={0}` to renderCamera() in App.js
It should now look like:

      `<RNCamera
        ref={ref => {
          this.camera = ref;
        }}
        style={{
          flex: 1,
        }}
        googleVisionBarcodeType={0}
        type={this.state.type}
        flashMode={this.state.flash}
        autoFocus={this.state.autoFocus}
        zoom={this.state.zoom}
        whiteBalance={this.state.whiteBalance}
        ratio={this.state.ratio}
        faceDetectionLandmarks={RNCamera.Constants.FaceDetection.Landmarks.all}
        onFacesDetected={this.onFacesDetected}
        onFaceDetectionError={this.onFaceDetectionError}
        focusDepth={this.state.depth}
        permissionDialogTitle={'Permission to use camera'}
        permissionDialogMessage={'We need your permission to use your camera phone'}
      >`

**Comment by sibelius** [comment]
Gonna track this in react-native-camera repo

**Comment by jgfidelis** [comment]
Should be fixed now
